heat_template_version: 2013-05-23

description: This template deploys 2 Servers behind a Load Balancer

parameters:
  image:
    type: string
    description: Image used for servers
    default: CentOS-7
  key:
    type: string
    description: SSH key to connect to the servers
    default: userkey
  flavor:
    type: string
    description: flavor used by the web servers
    default: Micro-Small
  public_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: public-floating-601
  

resources:
  apache_servergroup:
    type: OS::Nova::ServerGroup
    properties:
      #policies: ['affinity']
      policies: ['anti-affinity']


  network:
    type: lib/private_network.yaml
    properties:
      public_network: { get_param: public_network }

  load_balancer:
    type: lib/load_balancer.yaml
    properties:
      #public_network: { get_param: public_network }
      private_subnet: {get_attr: [network, private_subnet_id]}

  apacheserver1:
    type: lib/apacheserver_lb_sg.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      pool_id: {get_attr: [load_balancer, pool_resource]}
      private_network: { get_attr: [network, name] }
      servergroup_id: {get_resource: apache_servergroup}

  apacheserver2:
    type: lib/apacheserver_lb_sg.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      pool_id: {get_attr: [load_balancer, pool_resource]}
      private_network: { get_attr: [network, name] }
      servergroup_id: {get_resource: apache_servergroup}
  
  floating_ip1:
    type: lib/floating_ip.yaml
    properties:
      port: { get_attr: [apacheserver1, port] }
      public_network: { get_param: public_network }

  floating_ip2:
    type: lib/floating_ip.yaml
    properties:
      port: { get_attr: [apacheserver2, port] }
      public_network: { get_param: public_network }

outputs:
  lb_vip:
    description: The IP address of load_balancer
    value: {get_attr: [load_balancer, floating_ip]}





