heat_template_version: 2013-05-23

description: This template deploys a simple apache server with floating IP

parameters:
  image:
    type: string
    description: Image used for servers
    default: CentOS-7
  key:
    type: string
    description: SSH key to connect to the servers
    default: userkey
  flavor:
    type: string
    description: flavor used by the web servers
    default: Micro-Small
  public_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: public-floating-601
  

resources:

  web_server_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: web_server_security_group
      rules:
        - protocol: icmp
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80

  private_network:
    type: OS::Neutron::Net

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_network }
      cidr: 10.10.10.0/24
      dns_nameservers:
        - 8.8.8.8

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_network }

  router-interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet: { get_resource: private_subnet }

  apache_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: private_network }
      security_groups:
        - { get_resource: web_server_security_group }

  apache_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - port: { get_resource: apache_port }
      user_data_format: RAW
      user_data: |
            #!/bin/bash

            sudo -i
            yum install httpd -y
            yum install php -y
            cd /root
            git clone https://github.com/ChandraVenkatapathy/CL.git
            cp CL/showip.php /var/www/html/.
            service httpd start
            #more /var/www/html/index.html


  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }

  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: apache_port }

outputs:
  instance_name:
    description: Name of the instance
    value: { get_attr: [apache_instance, name] }
  instance_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [floating_ip, floating_ip_address] }
